@startuml
!pragma layout smetana

class Main {
+ static void main(String[] args)
}


class TextileHouse{
}

class ProductManager{
}

class FabricFinder{
}

class User {
- String username
- String password
- ArrayList<Product> savedList
- Collection<Product> getOrder
+ User(String username, String password)
+ String toString()
+ void addToSavedList(Product product)
- void addToOrderList(Product product)
+ String getUsername()
+ ArrayList<Product> getSavedList()
+ ArrayList<Product> getOrderList()
}

class Textile {}

class TextUI {}

class FileIO {}

Main *-- TextileHouse
TextileHouse *-- ProductManager
ProductManager *-- Textile
ProductManager *-- FabricFinder
TextileHouse *-- Textile
TextileHouse *-- User
User *-- Textile
@enduml