@startuml
!pragma layout smetana

class Main {
+ static void main(String[] args)
}


class TextileService{
- String name
- String textilesDataPath
- String userDataPath
- HashMap<String, String> userData
- User currentUser
- TextUI ui
- FileIO io
- TextileManager manager
+ TextileService(String name)
- void startTextileService()
- void createUser()
- void addUser(User u)
- void loadUserData()
- void loadSavedList()
- void homeMenu()
}

class TextileManager{
- TextUI
- FileIO
- ArrayList<Textiles> textiles
- User currentUser
- TextileService textileService
}

class FabricFinder{
}

class Login{
}

class User {
- String username
- String password
- ArrayList<Textile> savedList
- Collection<Textile> getOrder
+ User(String username, String password)
+ String toString()
+ void addToSavedList(Textile textile)
- void addToOrderList(Textile textile)
+ String getUsername()
+ ArrayList<Textile> getSavedList()
+ ArrayList<Textile> getOrderList()
}

class Textile {}

package "util" {

class TextUI {
- Scanner scan
+ void displayMsg(String msg)
+ int displayHomeMenu(String msg)
+ int promptNumeric(String msg)
+ String promptText(String msg)
}

class FileIO {
+ HashMap<String, String> readUserData(String path)
+ ArrayList<Movie> readTextileData(String path)
+ void SaveUserData(String userAsText, String path)
+ void saveTextileList(String username, ArrayList<Textile> savedList, String listType)
+ ArrayList<Textile> loadTextileList(String username, String listType)
}
}

Main *-- TextileService
TextileService *-- FileIO
TextileService *-- TextUI
TextileService *-- User
TextileService *-- TextileManager
TextileManager *-- Textile
TextileManager *-- FabricFinder
TextileService *-- Textile
User *-- Textile
@enduml