@startuml
!pragma layout smetana

class Main {
+ static void main(String[] args)
}


class TextileHouse{
- String name
- String textilesDataPath
- String userDataPath
- HashMap<String, String> userData
- User currentUser
- TextUI ui
- FileIO io
- ProductManager manager
+ TextileHouse(String name)
- void startTextileHouse()
- void createUser()
- void addUser(User u)
- void loadUserData()
- void loadWatchlist()
- void loadPrevWatched()
- void homeMenu()
}

class ProductManager{
- TextUI
- FileIO
- ArrayList<Textiles> textiles
- User currentUser
- TextileHouse textileHouse
}

class FabricFinder{
}

class User {
- String username
- String password
- ArrayList<Product> savedList
- Collection<Product> getOrder
+ User(String username, String password)
+ String toString()
+ void addToSavedList(Product product)
- void addToOrderList(Product product)
+ String getUsername()
+ ArrayList<Product> getSavedList()
+ ArrayList<Product> getOrderList()
}

class Textile {}

package "util" {

class TextUI {
- Scanner scan
+ void displayMsg(String msg)
+ int displayHomeMenu(String msg)
+ int promptNumeric(String msg)
+ String promptText(String msg)
}

class FileIO {
+ HashMap<String, String> readUserData(String path)
+ ArrayList<Movie> readTextileData(String path)
+ void SaveUserData(String userAsText, String path)
+ void saveTextileList(String username, ArrayList<Textile> watchlist, String listType)
+ ArrayList<Textile> loadTextileList(String username, String listType)
}
}

Main *-- TextileHouse
TextileHouse *-- FileIO
TextileHouse *-- TextUI
TextileHouse *-- User
TextileHouse *-- ProductManager
ProductManager *-- Textile
ProductManager *-- FabricFinder
TextileHouse *-- Textile
User *-- Textile
@enduml