@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

object TextileHouse
object LoginMenu
object Home
object Product
object Saved
object User
object Basket
object Payment

TextileHouse *-- LoginMenu
TextileHouse *-- Home
TextileHouse *-- User
TextileHouse *-- Product

Product --* Saved
Product --* Basket

User *-- Saved
User *-- Basket

Basket --* Payment





@enduml